# Docker Compose для разработки
services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: forum_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
    networks:
      - ai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 0.5G
          cpus: '1.0'
        reservations:
          memory: 0.5G
          cpus: '1.0'

volumes:
  postgres_data:
    driver: local

networks:
  ai_network:
    driver: bridge
