"""Fix User relationship mappings

Revision ID: 784bb7b2aa5e
Revises: eb5dff0465a3
Create Date: 2025-08-20 10:44:27.045416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784bb7b2aa5e'
down_revision: Union[str, Sequence[str], None] = 'eb5dff0465a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
