"""alter document field metadata

Revision ID: 79be894859d1
Revises: 7c2cdcf2172d
Create Date: 2025-10-04 08:15:53.260740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79be894859d1'
down_revision: Union[str, Sequence[str], None] = '7c2cdcf2172d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'meta_data')
    op.drop_column('documents', 'image_path')
    # ### end Alembic commands ###
