"""Create users profile

Revision ID: 04729a470680
Revises: de2929c868e2
Create Date: 2025-08-05 11:30:30.313391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04729a470680'
down_revision: Union[str, Sequence[str], None] = 'de2929c868e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('subject_level', sa.String(), nullable=False),
    sa.Column('subject_description', sa.String(), nullable=True),
    sa.Column('subject_language', sa.Enum('en', 'ru', 'by', 'pl', 'ua', name='language'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('learn_mode', sa.Enum('offline', 'online', 'both', name='learn_mode', native_enum=False), nullable=True),
    sa.Column('working_hours', sa.String(), nullable=True),
    sa.Column('working_days', sa.String(), nullable=True),
    sa.Column('subject_status', sa.Enum('pending', 'active', 'disabled', 'blocked', 'deleted', name='subject_status', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('language', sa.Enum('en', 'ru', 'by', 'pl', 'ua', name='default_language', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('date_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('booked_hours', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december', name='month', native_enum=False), nullable=True),
    sa.Column('working_days', sa.ARRAY(sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='days of week', native_enum=False)), nullable=True),
    sa.Column('working_hours', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_schedule')
    op.drop_table('subject_schedule')
    op.drop_table('user_profile')
    op.drop_table('subjects')
    # ### end Alembic commands ###
