"""Add categories and subcategories for topics

Revision ID: 3ca9d72fe2ba
Revises: 3d4ef75fee1e
Create Date: 2025-08-04 12:23:08.354729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ca9d72fe2ba"
down_revision: Union[str, Sequence[str], None] = "3d4ef75fee1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "subcategories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subcategories_category_id"), "subcategories", ["category_id"], unique=False)
    op.create_index(op.f("ix_subcategories_id"), "subcategories", ["id"], unique=False)
    op.create_index(op.f("ix_subcategories_name"), "subcategories", ["name"], unique=False)
    op.create_index(op.f("ix_subcategories_slug"), "subcategories", ["slug"], unique=False)
    op.add_column("topics", sa.Column("category_id", sa.Integer(), nullable=True))
    op.add_column("topics", sa.Column("subcategory_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_topics_category_id"), "topics", ["category_id"], unique=False)
    op.create_index(op.f("ix_topics_subcategory_id"), "topics", ["subcategory_id"], unique=False)
    op.create_foreign_key(None, "topics", "subcategories", ["subcategory_id"], ["id"])
    op.create_foreign_key(None, "topics", "categories", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "topics", type_="foreignkey")
    op.drop_constraint(None, "topics", type_="foreignkey")
    op.drop_index(op.f("ix_topics_subcategory_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_category_id"), table_name="topics")
    op.drop_column("topics", "subcategory_id")
    op.drop_column("topics", "category_id")
    op.drop_index(op.f("ix_subcategories_slug"), table_name="subcategories")
    op.drop_index(op.f("ix_subcategories_name"), table_name="subcategories")
    op.drop_index(op.f("ix_subcategories_id"), table_name="subcategories")
    op.drop_index(op.f("ix_subcategories_category_id"), table_name="subcategories")
    op.drop_table("subcategories")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
