"""add message and task type to TASK

Revision ID: 4ee7a8146990
Revises: 0f157f2ed205
Create Date: 2025-08-14 10:48:28.848856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee7a8146990'
down_revision: Union[str, Sequence[str], None] = '0f157f2ed205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('message_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tasks_message_id'), 'tasks', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_message_id'), table_name='tasks')
    op.drop_column('tasks', 'type')
    op.drop_column('tasks', 'message_id')
    # ### end Alembic commands ###
