"""add task type

Revision ID: 967111b05a4c
Revises: 4be0d8b7669d
Create Date: 2025-08-25 17:21:50.160804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967111b05a4c'
down_revision: Union[str, Sequence[str], None] = '4be0d8b7669d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('task_type', sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', name='task_type', native_enum=False), nullable=True))
    op.add_column('tasks', sa.Column('task_type', sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', name='task_type', native_enum=False), nullable=True))
    op.drop_column('tasks', 'type')
    op.add_column('topics', sa.Column('task_type', sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', name='task_type', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'task_type')
    op.add_column('tasks', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'task_type')
    op.drop_column('messages', 'task_type')
    # ### end Alembic commands ###
