"""Create quiz-models

Revision ID: 7256cff578f1
Revises: 967111b05a4c
Create Date: 2025-09-28 12:05:07.745226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7256cff578f1'
down_revision: Union[str, Sequence[str], None] = '967111b05a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', 'help', name='task_type', native_enum=False),
               existing_nullable=True)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', 'help', name='task_type', native_enum=False),
               existing_nullable=True)
    op.alter_column('topics', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', 'help', name='task_type', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'task_type',
               existing_type=sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', 'help', name='task_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', 'help', name='task_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('messages', 'task_type',
               existing_type=sa.Enum('general', 'question', 'tutorial', 'code', 'moderate', 'create', 'help', name='task_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
