"""Alter message examples

Revision ID: 4be0d8b7669d
Revises: 784bb7b2aa5e
Create Date: 2025-08-23 11:52:34.903468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be0d8b7669d'
down_revision: Union[str, Sequence[str], None] = '784bb7b2aa5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message_examples', sa.Column('profile_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_user_message_examples_character_id'), table_name='user_message_examples')
    op.drop_index(op.f('ix_user_message_examples_user_id'), table_name='user_message_examples')
    op.create_index(op.f('ix_user_message_examples_profile_id'), 'user_message_examples', ['profile_id'], unique=False)
    op.drop_constraint(op.f('user_message_examples_user_id_fkey'), 'user_message_examples', type_='foreignkey')
    op.create_foreign_key(None, 'user_message_examples', 'user_knowledge', ['profile_id'], ['id'])
    op.drop_column('user_message_examples', 'user_id')
    op.drop_column('user_message_examples', 'character_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message_examples', sa.Column('character_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_message_examples', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_message_examples', type_='foreignkey')
    op.create_foreign_key(op.f('user_message_examples_user_id_fkey'), 'user_message_examples', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_message_examples_profile_id'), table_name='user_message_examples')
    op.create_index(op.f('ix_user_message_examples_user_id'), 'user_message_examples', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_message_examples_character_id'), 'user_message_examples', ['character_id'], unique=False)
    op.drop_column('user_message_examples', 'profile_id')
    # ### end Alembic commands ###
