"""Fix rag models

Revision ID: ca0ccd1f7ce4
Revises: bbab98379662
Create Date: 2026-03-15 15:15:19.292387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca0ccd1f7ce4'
down_revision: Union[str, Sequence[str], None] = 'bbab98379662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_rag_usage', sa.Column('retrieved_count', sa.Integer(), nullable=True))
    op.add_column('tutor_rag_usage', sa.Column('provider', sa.String(length=64), nullable=True))
    op.add_column('tutor_rag_usage', sa.Column('llm_model', sa.String(length=128), nullable=True))
    op.add_column('tutor_rag_usage', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('tutor_rag_usage', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('tutor_rag_usage', 'topic',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tutor_rag_usage', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='session_id::uuid')
    op.alter_column('tutor_rag_usage', 'purpose',
               existing_type=postgresql.ENUM('lesson_draft', 'quiz_check', name='rag_usage_purpose'),
               type_=sa.Enum('lesson_draft', 'quiz_check', 'ingest', name='rag_usage_purpose', native_enum=False),
               existing_nullable=False)
    op.create_index('ix_tru_session_created', 'tutor_rag_usage', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_tru_user_topic_created', 'tutor_rag_usage', ['user_id', 'topic', 'created_at'], unique=False)
    op.create_foreign_key(None, 'tutor_rag_usage', 'tutor_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.add_column('user_topic_knowledge_chunks', sa.Column('source_label', sa.String(length=255), nullable=True))
    op.add_column('user_topic_knowledge_chunks', sa.Column('source_filename', sa.String(length=512), nullable=True))
    op.add_column('user_topic_knowledge_chunks', sa.Column('source_ref', sa.String(length=255), nullable=True))
    op.add_column('user_topic_knowledge_chunks', sa.Column('chunk_index', sa.Integer(), nullable=True))
    # Drop the integer sequence default before converting to UUID
    op.alter_column('user_topic_knowledge_chunks', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_topic_knowledge_chunks', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='gen_random_uuid()')
    op.alter_column('user_topic_knowledge_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_topic_knowledge_chunks', 'topic',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user_topic_knowledge_chunks', 'source_type',
               existing_type=postgresql.ENUM('manual', 'session', 'file', name='rag_source_type'),
               type_=sa.Enum('manual', 'session', 'file', 'ocr', 'import_api', name='rag_source_type', native_enum=False),
               existing_nullable=False)
    op.create_index('ix_utkc_user_source_filename', 'user_topic_knowledge_chunks', ['user_id', 'source_filename'], unique=False)
    op.create_index('ix_utkc_user_source_ref', 'user_topic_knowledge_chunks', ['user_id', 'source_ref'], unique=False)
    op.create_index('ix_utkc_user_topic_updated', 'user_topic_knowledge_chunks', ['user_id', 'topic', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_utkc_user_topic_updated', table_name='user_topic_knowledge_chunks')
    op.drop_index('ix_utkc_user_source_ref', table_name='user_topic_knowledge_chunks')
    op.drop_index('ix_utkc_user_source_filename', table_name='user_topic_knowledge_chunks')
    op.alter_column('user_topic_knowledge_chunks', 'source_type',
               existing_type=sa.Enum('manual', 'session', 'file', 'ocr', 'import_api', name='rag_source_type', native_enum=False),
               type_=postgresql.ENUM('manual', 'session', 'file', name='rag_source_type'),
               existing_nullable=False)
    op.alter_column('user_topic_knowledge_chunks', 'topic',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('user_topic_knowledge_chunks', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('user_topic_knowledge_chunks', 'chunk_index')
    op.drop_column('user_topic_knowledge_chunks', 'source_ref')
    op.drop_column('user_topic_knowledge_chunks', 'source_filename')
    op.drop_column('user_topic_knowledge_chunks', 'source_label')
    op.drop_constraint(None, 'tutor_rag_usage', type_='foreignkey')
    op.drop_index('ix_tru_user_topic_created', table_name='tutor_rag_usage')
    op.drop_index('ix_tru_session_created', table_name='tutor_rag_usage')
    op.alter_column('tutor_rag_usage', 'purpose',
               existing_type=sa.Enum('lesson_draft', 'quiz_check', 'ingest', name='rag_usage_purpose', native_enum=False),
               type_=postgresql.ENUM('lesson_draft', 'quiz_check', name='rag_usage_purpose'),
               existing_nullable=False)
    op.alter_column('tutor_rag_usage', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('tutor_rag_usage', 'topic',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('tutor_rag_usage', 'metadata_json')
    op.drop_column('tutor_rag_usage', 'latency_ms')
    op.drop_column('tutor_rag_usage', 'llm_model')
    op.drop_column('tutor_rag_usage', 'provider')
    op.drop_column('tutor_rag_usage', 'retrieved_count')
    # ### end Alembic commands ###
