"""quiz accessibility column

Revision ID: f5b687729d0e
Revises: 15b383200d62
Create Date: 2026-02-28 08:51:09.230668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f5b687729d0e'
down_revision: Union[str, Sequence[str], None] = '15b383200d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type using DO block to handle if exists
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE quizaccesstype AS ENUM ('PUBLIC', 'REGISTERED', 'PAID', 'SUBSCRIPTION', 'PRIVATE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.add_column('quizzes', sa.Column('access_type', 
                                        postgresql.ENUM('PUBLIC', 'REGISTERED', 'PAID', 'SUBSCRIPTION', 'PRIVATE', 
                                                       name='quizaccesstype', create_type=False), 
                                        nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE quizzes SET access_type = 'PUBLIC' WHERE access_type IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'access_type')
    # Drop enum type
    op.execute("DROP TYPE IF EXISTS quizaccesstype")
    # ### end Alembic commands ###
