"""Alter subject message table

Revision ID: 15b383200d62
Revises: bdb8d084acaf
Create Date: 2026-01-29 10:18:49.602006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15b383200d62'
down_revision: Union[str, Sequence[str], None] = 'bdb8d084acaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_schedule', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('subject_schedule', 'booked_hours',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('user_message', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_message', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_message', type_='foreignkey')
    op.drop_column('user_message', 'subject_id')
    op.alter_column('subject_schedule', 'booked_hours',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.drop_column('subject_schedule', 'created_at')
    # ### end Alembic commands ###
