"""add_mentor_mentee_system

Revision ID: 1fe684996047
Revises: f5b687729d0e
Create Date: 2026-03-01 10:52:13.241430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe684996047'
down_revision: Union[str, Sequence[str], None] = 'f5b687729d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_mentee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'REJECTED', name='mentor_mentee_status', native_enum=False), nullable=False),
    sa.Column('subscribe_to_quizzes', sa.Boolean(), nullable=False),
    sa.Column('subscribe_to_courses', sa.Boolean(), nullable=False),
    sa.Column('subscribe_to_subjects', sa.Boolean(), nullable=False),
    sa.Column('mentor_notes', sa.Text(), nullable=True, comment="Mentor's notes about the mentee"),
    sa.Column('mentee_notes', sa.Text(), nullable=True, comment="Mentee's notes about the mentor"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='When the relationship was accepted'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the relationship was completed'),
    sa.Column('initiated_by', sa.String(length=10), nullable=False, comment="'mentor' or 'mentee' - who created the request"),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mentor_id', 'mentee_id', name='unique_mentor_mentee_pair')
    )
    op.create_index('idx_mentee_id_status', 'mentor_mentee', ['mentee_id', 'status'], unique=False)
    op.create_index('idx_mentor_id_status', 'mentor_mentee', ['mentor_id', 'status'], unique=False)
    op.create_index(op.f('ix_mentor_mentee_mentee_id'), 'mentor_mentee', ['mentee_id'], unique=False)
    op.create_index(op.f('ix_mentor_mentee_mentor_id'), 'mentor_mentee', ['mentor_id'], unique=False)
    op.add_column('user_profile', sa.Column('mentor_bio', sa.Text(), nullable=True, comment="Mentor's biography and specialization"))
    op.add_column('user_profile', sa.Column('mentor_rate', sa.Float(), nullable=True, comment="Mentor's hourly rate"))
    op.add_column('user_profile', sa.Column('mentor_available', sa.Boolean(), nullable=True, comment='Is mentor available for new mentees'))
    op.add_column('user_profile', sa.Column('max_mentees', sa.Integer(), nullable=True, comment='Maximum number of mentees'))
    op.add_column('user_profile', sa.Column('learning_goals', sa.Text(), nullable=True, comment="Mentee's learning goals"))
    op.add_column('user_profile', sa.Column('preferred_learning_style', sa.String(length=50), nullable=True, comment='Preferred learning style'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'preferred_learning_style')
    op.drop_column('user_profile', 'learning_goals')
    op.drop_column('user_profile', 'max_mentees')
    op.drop_column('user_profile', 'mentor_available')
    op.drop_column('user_profile', 'mentor_rate')
    op.drop_column('user_profile', 'mentor_bio')
    op.drop_index(op.f('ix_mentor_mentee_mentor_id'), table_name='mentor_mentee')
    op.drop_index(op.f('ix_mentor_mentee_mentee_id'), table_name='mentor_mentee')
    op.drop_index('idx_mentor_id_status', table_name='mentor_mentee')
    op.drop_index('idx_mentee_id_status', table_name='mentor_mentee')
    op.drop_table('mentor_mentee')
    # ### end Alembic commands ###
