"""add tutor models

Revision ID: dade36f65f6b
Revises: 1fe684996047
Create Date: 2026-03-13 10:16:19.070755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dade36f65f6b'
down_revision: Union[str, Sequence[str], None] = '1fe684996047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_student_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('completed_topics', sa.JSON(), nullable=False, comment='[{"topic_id": 1, "score": 85.0, "completed_at": "..."}]'),
    sa.Column('current_level', sa.JSON(), nullable=False, comment='{"section_name": "beginner|intermediate|advanced"}'),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_time_minutes', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_student_progress_user_id'), 'tutor_student_progress', ['user_id'], unique=True)
    op.create_table('tutor_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='topic_level', native_enum=False), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('lesson_plan', sa.JSON(), nullable=False, comment='Structured lesson plan: list of questions with phases and timing'),
    sa.Column('system_prompt_template', sa.Text(), nullable=True, comment='Custom system prompt template for this topic (Jinja2-like placeholders)'),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=True, comment='List of prerequisite topic IDs'),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='topic_status', native_enum=False), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_topics_section'), 'tutor_topics', ['section'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'abandoned', name='session_status', native_enum=False), nullable=False),
    sa.Column('current_phase', sa.Enum('intro', 'theory', 'dialog', 'quiz', 'summary', name='lesson_phase', native_enum=False), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI-generated summary after session completion'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Extra data: mode (voice/text), LLM model, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['tutor_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_sessions_topic_id'), 'tutor_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_tutor_sessions_user_id'), 'tutor_sessions', ['user_id'], unique=False)
    op.create_table('tutor_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'voice_transcript', 'theory', 'question', 'quiz', 'code', 'diagram', name='message_type', native_enum=False), nullable=False),
    sa.Column('phase', sa.Enum('intro', 'theory', 'dialog', 'quiz', 'summary', name='message_phase', native_enum=False), nullable=False),
    sa.Column('question_id', sa.String(length=100), nullable=True, comment='Linked question ID from lesson_plan'),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_messages_session_id'), 'tutor_messages', ['session_id'], unique=False)
    op.create_table('tutor_question_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True, comment='AI feedback on the answer'),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('intro', 'theory', 'dialog', 'quiz', 'summary', name='question_phase', native_enum=False), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_question_results_session_id'), 'tutor_question_results', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_question_results_session_id'), table_name='tutor_question_results')
    op.drop_table('tutor_question_results')
    op.drop_index(op.f('ix_tutor_messages_session_id'), table_name='tutor_messages')
    op.drop_table('tutor_messages')
    op.drop_index(op.f('ix_tutor_sessions_user_id'), table_name='tutor_sessions')
    op.drop_index(op.f('ix_tutor_sessions_topic_id'), table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index(op.f('ix_tutor_topics_section'), table_name='tutor_topics')
    op.drop_table('tutor_topics')
    op.drop_index(op.f('ix_tutor_student_progress_user_id'), table_name='tutor_student_progress')
    op.drop_table('tutor_student_progress')
    # ### end Alembic commands ###
