"""Add payments models

Revision ID: 16846e06d0b8
Revises: ca0ccd1f7ce4
Create Date: 2026-03-19 11:00:22.728160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16846e06d0b8'
down_revision: Union[str, Sequence[str], None] = 'ca0ccd1f7ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User whose balance is affected'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Monetary amount. Always >= 0 except admin_adjustment which can be negative. Direction determined by transaction_type.'),
    sa.Column('transaction_type', sa.Enum('topup_stub', 'reward_forum_topic', 'reward_public_quiz', 'reward_ai_course', 'admin_adjustment', 'refund_to_student', 'spend_quiz', 'spend_ai_tokens', 'spend_course_access', 'spend_booking', 'transfer_to_mentor', 'withdraw_stub', 'reserve', 'release', name='transaction_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'canceled', 'reversed', name='transaction_status', native_enum=False), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment="Entity kind: 'topic','quiz','subject_schedule','ai_session', etc."),
    sa.Column('reference_id', sa.Integer(), nullable=True, comment='PK of the referenced entity'),
    sa.Column('counterpart_user_id', sa.Integer(), nullable=True, comment='Other party in a transfer (mentor or student)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False, comment='Caller-generated unique key; prevents double charges/rewards'),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True, comment='Set only for admin_adjustment type'),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=True, comment='Total tokens consumed (prompt + completion)'),
    sa.Column('ai_tokens_prompt', sa.Integer(), nullable=True, comment='OpenAI prompt tokens'),
    sa.Column('ai_tokens_completion', sa.Integer(), nullable=True, comment='OpenAI completion tokens'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='Extra context: quiz title, model name, booking date, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counterpart_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('idempotency_key', name='uq_btx_idempotency')
    )
    op.create_index(op.f('ix_balance_transactions_counterpart_user_id'), 'balance_transactions', ['counterpart_user_id'], unique=False)
    op.create_index(op.f('ix_balance_transactions_created_at'), 'balance_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_balance_transactions_status'), 'balance_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_balance_transactions_transaction_type'), 'balance_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_balance_transactions_user_id'), 'balance_transactions', ['user_id'], unique=False)
    op.create_index('ix_btx_counterpart', 'balance_transactions', ['counterpart_user_id'], unique=False)
    op.create_index('ix_btx_reference', 'balance_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_btx_type_status', 'balance_transactions', ['transaction_type', 'status'], unique=False)
    op.create_index('ix_btx_user_created', 'balance_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('user_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('available_credits', sa.Numeric(precision=15, scale=2), nullable=False, comment='Credits freely available for spending'),
    sa.Column('reserved_credits', sa.Numeric(precision=15, scale=2), nullable=False, comment='Credits frozen for pending bookings/transactions'),
    sa.Column('total_earned', sa.Numeric(precision=15, scale=2), nullable=False, comment='Lifetime credits earned (rewards + topups + refunds received)'),
    sa.Column('total_spent', sa.Numeric(precision=15, scale=2), nullable=False, comment='Lifetime credits spent (purchases + transfers out + withdrawals)'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Incremented on every update; compare before writing to detect races'),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_balance_user')
    )
    op.create_index('ix_user_balance_user_id', 'user_balance', ['user_id'], unique=False)
    op.create_table('topup_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=15, scale=2), nullable=False, comment='Credits requested'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment="e.g. 'bank_transfer', 'stripe_stub'"),
    sa.Column('external_reference', sa.String(length=200), nullable=True, comment='External payment ID (masked if sensitive)'),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'canceled', name='topup_request_status', native_enum=False), nullable=False),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['balance_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topup_requests_status'), 'topup_requests', ['status'], unique=False)
    op.create_index(op.f('ix_topup_requests_user_id'), 'topup_requests', ['user_id'], unique=False)
    op.create_index('ix_topup_user_created', 'topup_requests', ['user_id', 'created_at'], unique=False)
    op.create_table('withdraw_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=15, scale=2), nullable=False, comment='Credits to withdraw'),
    sa.Column('payout_method', sa.String(length=50), nullable=True, comment="e.g. 'bank_transfer', 'card_stub'"),
    sa.Column('payout_details_masked', sa.String(length=200), nullable=True, comment="Masked destination e.g. '**** **** **** 1234'"),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'canceled', name='withdraw_request_status', native_enum=False), nullable=False),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['balance_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdraw_requests_status'), 'withdraw_requests', ['status'], unique=False)
    op.create_index(op.f('ix_withdraw_requests_user_id'), 'withdraw_requests', ['user_id'], unique=False)
    op.create_index('ix_withdraw_user_created', 'withdraw_requests', ['user_id', 'created_at'], unique=False)
    op.create_table('topic_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'user_id', name='uq_topic_vote')
    )
    op.create_index(op.f('ix_topic_votes_topic_id'), 'topic_votes', ['topic_id'], unique=False)
    op.create_index('ix_topic_votes_user_id', 'topic_votes', ['user_id'], unique=False)
    op.alter_column('user_profile', 'mentor_bio',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Mentor's biography and specialization",
               existing_nullable=True)
    op.alter_column('user_profile', 'mentor_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment="Mentor's hourly rate",
               existing_nullable=True)
    op.alter_column('user_profile', 'mentor_available',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Is mentor available for new mentees',
               existing_nullable=True)
    op.alter_column('user_profile', 'max_mentees',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum number of mentees',
               existing_nullable=True)
    op.alter_column('user_profile', 'learning_goals',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Mentee's learning goals",
               existing_nullable=True)
    op.alter_column('user_profile', 'preferred_learning_style',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Preferred learning style',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'preferred_learning_style',
               existing_type=sa.VARCHAR(length=50),
               comment='Preferred learning style',
               existing_nullable=True)
    op.alter_column('user_profile', 'learning_goals',
               existing_type=sa.TEXT(),
               comment="Mentee's learning goals",
               existing_nullable=True)
    op.alter_column('user_profile', 'max_mentees',
               existing_type=sa.INTEGER(),
               comment='Maximum number of mentees',
               existing_nullable=True)
    op.alter_column('user_profile', 'mentor_available',
               existing_type=sa.BOOLEAN(),
               comment='Is mentor available for new mentees',
               existing_nullable=True)
    op.alter_column('user_profile', 'mentor_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment="Mentor's hourly rate",
               existing_nullable=True)
    op.alter_column('user_profile', 'mentor_bio',
               existing_type=sa.TEXT(),
               comment="Mentor's biography and specialization",
               existing_nullable=True)
    op.drop_index('ix_topic_votes_user_id', table_name='topic_votes')
    op.drop_index(op.f('ix_topic_votes_topic_id'), table_name='topic_votes')
    op.drop_table('topic_votes')
    op.drop_index('ix_withdraw_user_created', table_name='withdraw_requests')
    op.drop_index(op.f('ix_withdraw_requests_user_id'), table_name='withdraw_requests')
    op.drop_index(op.f('ix_withdraw_requests_status'), table_name='withdraw_requests')
    op.drop_table('withdraw_requests')
    op.drop_index('ix_topup_user_created', table_name='topup_requests')
    op.drop_index(op.f('ix_topup_requests_user_id'), table_name='topup_requests')
    op.drop_index(op.f('ix_topup_requests_status'), table_name='topup_requests')
    op.drop_table('topup_requests')
    op.drop_index('ix_user_balance_user_id', table_name='user_balance')
    op.drop_table('user_balance')
    op.drop_index('ix_btx_user_created', table_name='balance_transactions')
    op.drop_index('ix_btx_type_status', table_name='balance_transactions')
    op.drop_index('ix_btx_reference', table_name='balance_transactions')
    op.drop_index('ix_btx_counterpart', table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_user_id'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_transaction_type'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_status'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_created_at'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_counterpart_user_id'), table_name='balance_transactions')
    op.drop_table('balance_transactions')
    # ### end Alembic commands ###
