"""add rag models

Revision ID: bbab98379662
Revises: dade36f65f6b
Create Date: 2026-03-15 09:05:22.540726

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbab98379662'
down_revision: Union[str, Sequence[str], None] = 'dade36f65f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_rag_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.Enum('lesson_draft', 'quiz_check', name='rag_usage_purpose'), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_rag_usage_session_id'), 'tutor_rag_usage', ['session_id'], unique=False)
    op.create_index(op.f('ix_tutor_rag_usage_topic'), 'tutor_rag_usage', ['topic'], unique=False)
    op.create_index(op.f('ix_tutor_rag_usage_user_id'), 'tutor_rag_usage', ['user_id'], unique=False)
    op.create_table('user_topic_knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.Enum('manual', 'session', 'file', name='rag_source_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_topic_knowledge_chunks_topic'), 'user_topic_knowledge_chunks', ['topic'], unique=False)
    op.create_index(op.f('ix_user_topic_knowledge_chunks_user_id'), 'user_topic_knowledge_chunks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_topic_knowledge_chunks_user_id'), table_name='user_topic_knowledge_chunks')
    op.drop_index(op.f('ix_user_topic_knowledge_chunks_topic'), table_name='user_topic_knowledge_chunks')
    op.drop_table('user_topic_knowledge_chunks')
    op.drop_index(op.f('ix_tutor_rag_usage_user_id'), table_name='tutor_rag_usage')
    op.drop_index(op.f('ix_tutor_rag_usage_topic'), table_name='tutor_rag_usage')
    op.drop_index(op.f('ix_tutor_rag_usage_session_id'), table_name='tutor_rag_usage')
    op.drop_table('tutor_rag_usage')
    # ### end Alembic commands ###
