"""anti-cheat bot

Revision ID: 517f0e36dd6c
Revises: 16846e06d0b8
Create Date: 2026-03-21 09:49:32.268283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517f0e36dd6c'
down_revision: Union[str, Sequence[str], None] = '16846e06d0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anti_cheat_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=32), nullable=False, comment="Type of session: 'ai_tutor' or 'quiz'"),
    sa.Column('incident_type', sa.String(length=64), nullable=False, comment="Type of violation: 'focus_loss', 'dev_tools_detected', 'screenshot_blocked', etc."),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional context: user_agent, ip, browser_info, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anti_cheat_incidents_created_at'), 'anti_cheat_incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_anti_cheat_incidents_session_id'), 'anti_cheat_incidents', ['session_id'], unique=False)
    op.create_index(op.f('ix_anti_cheat_incidents_user_id'), 'anti_cheat_incidents', ['user_id'], unique=False)
    op.add_column('quizzes', sa.Column('anti_cheat_config', sa.JSON(), nullable=True, comment='Anti-cheat configuration for exam mode: enabled, methods, warnings_limit, etc.'))
    op.add_column('tutor_student_progress', sa.Column('anti_cheat_config', sa.JSON(), nullable=True, comment='Anti-cheat configuration for exam mode: enabled, methods, warnings_limit, etc.'))
    op.drop_index(op.f('ix_user_balance_user_id'), table_name='user_balance')
    op.create_index(op.f('ix_user_balance_user_id'), 'user_balance', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_balance_user_id'), table_name='user_balance')
    op.create_index(op.f('ix_user_balance_user_id'), 'user_balance', ['user_id'], unique=False)
    op.drop_column('tutor_student_progress', 'anti_cheat_config')
    op.drop_column('quizzes', 'anti_cheat_config')
    op.drop_index(op.f('ix_anti_cheat_incidents_user_id'), table_name='anti_cheat_incidents')
    op.drop_index(op.f('ix_anti_cheat_incidents_session_id'), table_name='anti_cheat_incidents')
    op.drop_index(op.f('ix_anti_cheat_incidents_created_at'), table_name='anti_cheat_incidents')
    op.drop_table('anti_cheat_incidents')
    # ### end Alembic commands ###
